<?xml version="1.0"?>
<!--
Copyright (c) 2018, I3D Robotics Ltd.
Edited: 2019, Marti Morta Garriga, Wood.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="titania_camera" params="camera_name:=titania en_mesh:=false en_imu:=false">

    <xacro:property name="height" value="0.059"/>
    <xacro:property name="width" value="0.126"/>
    <xacro:property name="length" value="0.0655"/>
    <xacro:property name="baseline" value="0.09"/>
    <xacro:property name="img_w" value="1600"/>
    <xacro:property name="img_h" value="1600"/>
    <xacro:property name="mesh_file" value="package://i3dr_titania/mesh/titania.stl"/>
    <xacro:property name="mesh_offset_xyz" value="0 0 -0.07"/>
    <xacro:property name="mesh_offset_rpy" value="0 0 -${pi/2}"/>
    <xacro:property name="box_offset_xyz" value="0 0 0"/>
    <xacro:property name="box_offset_rpy" value="0 0 0"/>
    <xacro:property name="fov_rad" value="${57.8 * pi/180.0}"/>
    <xacro:property name="sim_w" value="${img_w/2}"/>
    <xacro:property name="sim_h" value="${img_h/2}"/>
    <xacro:property name="sim_rate" value="5"/>

    <material name="darkgrey">
        <color rgba= "0.1 0.1 0.1 1.0"/>
    </material>

    <link name="${camera_name}_cameraLeft_optical" />
    <link name="${camera_name}_cameraRight_optical" />
    <link name="${camera_name}_cameraLeft" />
    <link name="${camera_name}_cameraRight" />

    <link name="${camera_name}_depth_optical_frame" />

    <link name="${camera_name}_base_link" />

    <link name="${camera_name}_mount_base_link" />

    <xacro:if value="${(en_imu == 'true')}">
        <link name="${camera_name}_imu_link"/>
    </xacro:if>

    <link name="${camera_name}_mount_point_1"/>
    <link name="${camera_name}_mount_point_2"/>

    <link name="${camera_name}_probe_mount"/>

    <link name="${camera_name}_center">
        <pose>0 0 0 0 0 0</pose>

        <inertial>
            <mass value="5"/>
            <origin rpy="0 0 0" xyz="0 0 0.1"/>
            <inertia ixx="0.039" ixy="0" ixz="0" iyy="0.106" iyz="0" izz="0.0106"/>
        </inertial>
    
        <collision name="${camera_name}_center_collision">
            <geometry>
                <box size="${length} ${width} ${height}"/>
            </geometry>
        </collision>

        <visual>
            <xacro:if value="${(en_mesh == 'true')}">
                <origin xyz="${mesh_offset_xyz}" rpy="${mesh_offset_rpy}"/>
            </xacro:if>
            <xacro:if value="${(en_mesh == 'false')}">
                <origin xyz="${box_offset_xyz}" rpy="${box_offset_rpy}"/>
            </xacro:if>
            <geometry>
                <xacro:if value="${(en_mesh == 'true')}">
                    <mesh filename="${mesh_file}"/>
                </xacro:if>
                <xacro:if value="${(en_mesh == 'false')}">
                    <box size="${length} ${width} ${height}"/>
                </xacro:if>
            </geometry>
            <material name="darkgrey"/>
        </visual>
    </link>

    <xacro:if value="${(en_imu == 'true')}">
        <joint name="${camera_name}_imu_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
            <parent link="${camera_name}_base_link" />
            <child link="${camera_name}_imu_link" />
        </joint>
        <joint name="${camera_name}_imu_mount_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
            <parent link="${camera_name}_base_link" />
            <child link="${camera_name}_mount_base_link" />
        </joint>
    </xacro:if>
    <xacro:if value="${(en_imu == 'false')}">
        <joint name="${camera_name}_imu_mount_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="${camera_name}_base_link" />
            <child link="${camera_name}_mount_base_link" />
        </joint>
    </xacro:if>

    <joint name="${camera_name}_right_camera_joint" type="fixed">
        <parent link="${camera_name}_center"/>
        <child link="${camera_name}_cameraRight"/>
        <origin xyz="0 ${-baseline/2}  0" rpy="0 0 0" />
    </joint>

    <joint name="${camera_name}_left_camera_joint" type="fixed">
        <parent link="${camera_name}_center"/>
        <child link="${camera_name}_cameraLeft"/>
        <origin xyz="0 ${baseline/2}  0" rpy="0 0 0" />
    </joint>

    <joint name="${camera_name}_left_optical_joint" type="fixed">
        <parent link="${camera_name}_cameraLeft"/>
        <child link="${camera_name}_cameraLeft_optical"/>
        <!-- Correct for the optical frame orientation -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${(-pi/2)}" />
    </joint>

    <joint name="${camera_name}_right_optical_joint" type="fixed">
        <parent link="${camera_name}_cameraRight"/>
        <child link="${camera_name}_cameraRight_optical"/>
        <!-- Correct for the optical frame orientation -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${(-pi/2)}" />
    </joint>

    <joint name="${camera_name}_depth_optical_joint" type="fixed">
        <parent link="${camera_name}_cameraLeft_optical"/>
        <child link="${camera_name}_depth_optical_frame"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <joint name="${camera_name}_mount_center_joint" type="fixed">
        <parent link="${camera_name}_mount_base_link"/>
        <child link="${camera_name}_center"/>
        <origin xyz="0 0 0" rpy="0 0 ${-pi/2}" />
    </joint>

    <joint name="${camera_name}_probe_mount_joint" type="fixed">
        <parent link="${camera_name}_mount_base_link"/>
        <child link="${camera_name}_probe_mount"/>
        <origin xyz="${0} 0 ${0}" rpy="0 0 0" />
    </joint>

    <joint name="${camera_name}_mount_point_1_joint" type="fixed">
        <parent link="${camera_name}_mount_base_link"/>
        <child link="${camera_name}_mount_point_1"/>
        <origin xyz="${(0.03/2)-0.002} -0.007 ${-0.038/2}" rpy="0 0 0" />
    </joint>
    <joint name="${camera_name}_mount_point_2_joint" type="fixed">
        <parent link="${camera_name}_mount_base_link"/>
        <child link="${camera_name}_mount_point_2"/>
        <origin xyz="${(-0.03/2)-0.002} -0.007 ${-0.038/2}" rpy="0 0 0" />
    </joint>

    <xacro:macro name="optical_camera" params="name offset fov_rad:=^ sim_w:=^ sim_h:=^">
        <camera name="${name}">
            <pose>0 ${offset} 0 0 0 0</pose>
            <horizontal_fov>${fov_rad}</horizontal_fov>
            <image>
                <width>${sim_w}</width>
                <height>${sim_h}</height>
                <format>B8G8R8</format>
            </image>
            <clip>
                <near>0.02</near>
                <far>300</far>
            </clip>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.007</stddev>
            </noise>
      </camera>
    </xacro:macro>
    <gazebo reference="${camera_name}_cameraLeft">
      <sensor type="multicamera" name="stereo_camera">
        <update_rate>${sim_rate}</update_rate> <!-- reality 60fps on USB3-->
        <optical_camera name="left" offset="0" />
        <optical_camera name="right" offset="${-baseline}" />
        <plugin name="stereo_camera_controller" filename="libgazebo_ros_multicamera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>${sim_rate}</updateRate>
          <cameraName>${camera_name}</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>${camera_name}_cameraLeft_optical</frameName>
          <!--<rightFrameName>${camera_name}_cameraRight_optical</rightFrameName>-->
          <hackBaseline>${baseline}</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>
    </gazebo>




    <!--<gazebo reference="${camera_name}_cameraLeft">
      <sensor type="camera" name="camera_left">
        <update_rate>${sim_rate}</update_rate>
        <optical_camera name="left" />
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>${sim_rate}</updateRate>
          <cameraName>${camera_name}/left</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>${camera_name}_cameraLeft_optical</frameName>
        </plugin>
      </sensor>
    </gazebo>
    <gazebo reference="${camera_name}_cameraRight">
      <sensor type="camera" name="camera_right">
        <update_rate>${sim_rate}</update_rate>
        <optical_camera name="right" />
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>${sim_rate}</updateRate>
          <cameraName>${camera_name}/right</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>${camera_name}_cameraRight_optical</frameName>
        </plugin>
      </sensor>
    </gazebo>
    -->

    <gazebo reference="${camera_name}_center">
        <material>Gazebo/DarkGrey</material>
    </gazebo>

  </xacro:macro>

</robot>