name: ROS Build

on: [push]

jobs:    
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            rosdistro: melodic
            pythonprefix: python
          - os: ubuntu-20.04
            rosdistro: noetic
            pythonprefix: python3
    env:
      ROS_CI_DESKTOP: "`lsb_release -cs`"  # e.g. [trusty|xenial|...]
      ROSINSTALL_FILE: $GITHUB_WORKSPACE/dependencies.rosinstall
      CATKIN_OPTIONS: $GITHUB_WORKSPACE/catkin.options
      ROS_PARALLEL_JOBS: '-j8 -l6'
      ROS_DISTRO: ${{ matrix.rosdistro }}
      PYTHON_PREFIX: ${{ matrix.pythonprefix }}
      PYLON_ROOT: /opt/pylon
    steps:
      - uses: actions/checkout@v2
      - name: Install Pylon
        run: |
          wget -O pylon.deb https://www.baslerweb.com/fp-1589378344/media/downloads/software/pylon_software/pylon_6.1.1.19861-deb0_amd64.deb
          sudo dpkg -i pylon.deb
          echo "Pylon root $PYLON_ROOT"
          $PYLON_ROOT/bin/pylon-config --version-major
      - name: Install ROS
        run: |
            sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
            sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
            sudo apt-get update -qq
            sudo apt-get install dpkg
            sudo apt-get install -y $PYTHON_PREFIX-catkin-tools $PYTHON_PREFIX-catkin-pkg $PYTHON_PREFIX-rosdep $PYTHON_PREFIX-wstool ros-$ROS_DISTRO-cv-bridge ros-$ROS_DISTRO-image-transport ros-$ROS_DISTRO-roslint
            sudo apt-get install -y ros-$ROS_DISTRO-nodelet-core ros-$ROS_DISTRO-ddynamic-reconfigure frei0r-plugins-dev
            source /opt/ros/$ROS_DISTRO/setup.bash
            # Prepare rosdep to install dependencies.
            sudo rosdep init
            rosdep update --include-eol-distros  # Support EOL distros.
      - name: Pylon rosdep
        run: |
            sudo sh -c 'echo "yaml https://raw.githubusercontent.com/i3drobotics/pylon_camera/main/rosdep/pylon_sdk.yaml " > /etc/ros/rosdep/sources.list.d/15-plyon_camera.list'
            rosdep update --include-eol-distros
      - name: Setup ROS workspace
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws
          catkin build
          wstool init src $GITHUB_WORKSPACE/install/i3dr_titania_https.rosinstall
          rosdep install --from-paths src --ignore-src -r -y
      - name: Build workspace
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd ~/catkin_ws
          catkin build
